# Generated by Django 5.2.7 on 2026-01-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaapp', '0003_alter_mascota_duenyos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.FileField(blank=True, upload_to='fotitos/'),
        ),
    ]
